# Taps
tap 'homebrew/cask'
tap 'homebrew/cask-fonts'
tap 'homebrew/cask-versions'
tap 'homebrew/bundle'
tap 'nicoverbruggen/homebrew-cask'

# Install Binaries
brew 'bat'
brew 'coreutils'
brew 'git'
brew 'gh'
brew 'grep'
brew 'httpie'
brew 'mackup'
brew 'mas'
brew 'pkg-config' # https://github.com/driesvints/dotfiles/issues/20
brew 'trash'
brew 'tree'
brew 'wget'
brew 'neovim'
brew 'ripgrep'
brew 'tmux'
brew 'neofetch'
brew 'exa'
brew 'openssl'

# Development
brew 'postgresql'
brew 'mysql'
brew 'nginx'
brew 'node'
brew 'redis'
brew 'yarn'
brew 'nvm'
brew 'pnpm'
brew 'jupyterlab'

# ZSH, OH-MY-ZSH plugins
brew 'autojump'
brew 'zsh-completions'

# Apps
cask 'google-chrome'
cask 'docker'
cask 'firefox'
cask 'insomnia'
cask 'rectangle'
cask 'dropbox'
# Checks battery health
cask 'coconutbattery'
cask 'warp'
cask 'visual-studio-code'
cask 'slack'
cask 'discord'
cask 'figma'

# Fonts
cask 'font-fira-code'
cask 'font-lato'
cask 'font-hack-nerd-font'
